# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2576bdd510bd5f40ce8708f1ac53ec3ff76ceda1476f5bd53547726e1f4fa0d94dc51d5cf539c5210e8cff1735a4f0c4db37ffc00871818b4f4e5da5f05c66af
  GMAIL_USERNAME: sathibabu.patchipala@gmail.com
  GMAIL_PASSWORD: 9989934391S

test:
  secret_key_base: f59d8266e7773279aeb7ff3ba6ef31cd98f1b77fb8fb7c2b6c75842aefce9fbcdf3f7035b65d75089c41c6b7b9b1a0ddb6e392a1a82a06a93c4f132fc15a35fa
  
# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>



 